#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
v23.100: de woordkaarten van Cervantes worden kaarten in plaats van woordenboekregels
(punt 14 en 15).

## Wat er mis was

Van de 1376 Cervantes-woorden verklapten er 80 het Spaanse antwoord op de Nederlandse kant, en 295
stapelden meerdere betekenissen op de voorkant, waarvan 102 er meer dan twee.

    "a pesar de = ondanks; wegen"          -> antwoord: pesar
    "overblijven; afspreken; quedar bien = goed staan"  -> antwoord: quedar
    "vinger; teen: dedo del pie"           -> antwoord: dedo

De eerste twee vragen je een woord te raden dat er al staat. De derde ook. En de rest vraagt je te
raden wélke van drie betekenissen er bedoeld wordt, wat geen taalvraag is maar een gokspel.

Dat komt doordat het `nl`-veld uit een frequentielijst komt. Daar is het een woordenboekvertaling,
en die hoort alles te vermelden. Op een kaart is het een vraag, en die hoort er één te stellen.

## Wat er nu gebeurt

Eén betekenis op de vraagkant, de rest in een nieuw veld `meer` dat pas ná het antwoord verschijnt.
311 kaarten veranderen (296 van Cervantes en 15 kernwoorden); de rest blijft zoals hij was.

De splitsing is mechanisch en de regels staan hieronder, want ze zijn nagelopen op alle 1376:

  - splitsen op puntkomma's buiten haakjes, zodat "pakken, nemen (Spanje; grof in Lat-Am!)" heel
    blijft;
  - een segment gaat naar achteren zodra het een woord deelt met het Spaanse antwoord, een `=`
    bevat, of na een dubbele punt Spaans geeft;
  - een haakje dat Spaans bevat wordt eruit gepeld en gaat ook naar achteren, zodat
    "Sint (San Juan = Sint Jan)" vooraan gewoon "Sint" wordt;
  - leenwoorden zijn geen lek. "virus", "club", "motor", "crisis", "chorizo": als de Nederlandse
    kant hetzelfde wóórd is als het Spaanse antwoord, is dat geen verklapping maar een cognaat, en
    die kaart blijft heel;
  - lekt élk segment, dan wordt de Nederlandse kant van de eerste "X = Y" de nieuwe voorkant. Zo
    wordt "te lo ruego = ik smeek je (van rogar)" vooraan "ik smeek je", met de uitdrukking erachter.

Nagemeten na afloop: nul kaarten waarvan de voorkant nog een woord deelt met het antwoord.

## En de app laat het zien

De achterkant van een woordkaart toont `meer` onder het antwoord, in kleiner grijs. Dat is precies
de plek waar een woordenboekregel wél thuishoort: als je het antwoord al weet.

Idempotent.
"""
import io, sys, os, re

WORTEL = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/espanol")
PAD = os.path.join(WORTEL, "index.html")
PAD_VER = os.path.join(WORTEL, "versie.txt")

NIEUW = "v23.100"

with io.open(PAD, encoding="utf-8") as f:
    src = f.read()

DOE_APP = "v23.100" not in src
with io.open(PAD_VER, encoding="utf-8") as f:
    huidig_ver = f.read().strip()
DOE_VER = huidig_ver != NIEUW

if not DOE_APP and not DOE_VER:
    print("al toegepast, niets te doen")
    sys.exit(0)

# ---- de achterkant van de kaart toont wat er nog meer is ----
A_ACHTER = '''    "<p class=\'big\' style=\'color:var(--accent)\'>"+back+"</p>"+
    "<span class=\'tag\'>"+wCur.tag+"</span>"+'''
N_ACHTER = '''    "<p class=\'big\' style=\'color:var(--accent)\'>"+back+"</p>"+
    /* v23.100: de rest van de betekenissen staat hier, ná het antwoord. Op de vraagkant maakte die
       stapel van een taalvraag een gokspel ("welke van de drie bedoelen ze?"); hier is het precies
       wat een woordenboekregel hoort te zijn: naslag voor wie het antwoord al heeft. */
    (wCur.meer ? "<p class=\'muted\' style=\'margin:2px 2px 0; font-size:.9rem\'>"+wCur.meer+"</p>" : "")+
    "<span class=\'tag\'>"+wCur.tag+"</span>"+'''

PAREN = [
  ('id:"cv5", es:"segundo", nl:"tweede; seconde", tag:"cerv-wie-je-bent", sl:"segundo"}',
   'id:"cv5", es:"segundo", nl:"tweede", tag:"cerv-wie-je-bent", sl:"segundo", meer:"seconde"}'),
  ('id:"cv6", es:"vino", nl:"wijn; hij/zij kwam (van venir)", tag:"cerv-eten", sl:"vino"}',
   'id:"cv6", es:"vino", nl:"wijn", tag:"cerv-eten", sl:"vino", meer:"hij/zij kwam (van venir)"}'),
  ('id:"cv7", es:"café", nl:"koffie; café", tag:"cerv-eten", sl:"cafe"}',
   'id:"cv7", es:"café", nl:"koffie", tag:"cerv-eten", sl:"cafe", meer:"café"}'),
  ('id:"cv9", es:"metros", nl:"meters; metro\'s", tag:"cerv-hoeveel", sl:"metros"}',
   'id:"cv9", es:"metros", nl:"meters", tag:"cerv-hoeveel", sl:"metros", meer:"metro\'s"}'),
  ('id:"cv11", es:"parada", nl:"halte; gestopt (v)", tag:"cerv-reizen", sl:"parada"}',
   'id:"cv11", es:"parada", nl:"halte", tag:"cerv-reizen", sl:"parada", meer:"gestopt (v)"}'),
  ('id:"cv22", es:"igual", nl:"gelijk, hetzelfde; misschien", tag:"cerv-bestaan", sl:"igual"}',
   'id:"cv22", es:"igual", nl:"gelijk, hetzelfde", tag:"cerv-bestaan", sl:"igual", meer:"misschien"}'),
  ('id:"cv25", es:"medio", nl:"half; midden; medio ambiente = milieu", tag:"cerv-winkelen", sl:"medio"}',
   'id:"cv25", es:"medio", nl:"half", tag:"cerv-winkelen", sl:"medio", meer:"midden; medio ambiente = milieu"}'),
  ('id:"cv26", es:"oído", nl:"gehoord; oor", tag:"cerv-lichaam", sl:"oido"}',
   'id:"cv26", es:"oído", nl:"gehoord", tag:"cerv-lichaam", sl:"oido", meer:"oor"}'),
  ('id:"cv27", es:"paz", nl:"vrede; déjame en paz = laat me met rust", tag:"cerv-politiek", sl:"paz"}',
   'id:"cv27", es:"paz", nl:"vrede", tag:"cerv-politiek", sl:"paz", meer:"déjame en paz = laat me met rust"}'),
  ('id:"cv31", es:"cielo", nl:"hemel, lucht; schat", tag:"cerv-natuur", sl:"cielo"}',
   'id:"cv31", es:"cielo", nl:"hemel, lucht", tag:"cerv-natuur", sl:"cielo", meer:"schat"}'),
  ('id:"cv34", es:"cambio", nl:"verandering; wisselgeld; en cambio = daarentegen", tag:"cerv-winkelen", sl:"cambio"}',
   'id:"cv34", es:"cambio", nl:"verandering", tag:"cerv-winkelen", sl:"cambio", meer:"wisselgeld; en cambio = daarentegen"}'),
  ('id:"cv36", es:"derecho", nl:"recht; rechts; rechtdoor", tag:"cerv-school", sl:"derecho"}',
   'id:"cv36", es:"derecho", nl:"recht", tag:"cerv-school", sl:"derecho", meer:"rechts; rechtdoor"}'),
  ('id:"cv37", es:"sexo", nl:"seks; geslacht", tag:"cerv-lichaam", sl:"sexo"}',
   'id:"cv37", es:"sexo", nl:"seks", tag:"cerv-lichaam", sl:"sexo", meer:"geslacht"}'),
  ('id:"cv39", es:"pie", nl:"voet; a pie = te voet", tag:"cerv-lichaam", sl:"pie"}',
   'id:"cv39", es:"pie", nl:"voet", tag:"cerv-lichaam", sl:"pie", meer:"a pie = te voet"}'),
  ('id:"cv41", es:"cita", nl:"afspraak; date; citaat", tag:"cerv-relaties", sl:"cita"}',
   'id:"cv41", es:"cita", nl:"afspraak", tag:"cerv-relaties", sl:"cita", meer:"date; citaat"}'),
  ('id:"cv42", es:"pobre", nl:"arm; arme", tag:"cerv-economie", sl:"pobre"}',
   'id:"cv42", es:"pobre", nl:"arm", tag:"cerv-economie", sl:"pobre", meer:"arme"}'),
  ('id:"cv46", es:"traje", nl:"pak, kostuum; ik bracht (van traer)", tag:"cerv-werk", sl:"traje"}',
   'id:"cv46", es:"traje", nl:"pak, kostuum", tag:"cerv-werk", sl:"traje", meer:"ik bracht (van traer)"}'),
  ('id:"cv52", es:"sal", nl:"zout; ga eruit (van salir)", tag:"cerv-eten", sl:"sal"}',
   'id:"cv52", es:"sal", nl:"zout", tag:"cerv-eten", sl:"sal", meer:"ga eruit (van salir)"}'),
  ('id:"cv53", es:"suelo", nl:"grond, vloer; ik pleeg te (van soler)", tag:"cerv-wonen", sl:"suelo"}',
   'id:"cv53", es:"suelo", nl:"grond, vloer", tag:"cerv-wonen", sl:"suelo", meer:"ik pleeg te (van soler)"}'),
  ('id:"cv73", es:"quedar", nl:"overblijven; afspreken; quedar bien = goed staan", tag:"cerv-vrije-tijd", sl:"quedar"}',
   'id:"cv73", es:"quedar", nl:"overblijven", tag:"cerv-vrije-tijd", sl:"quedar", meer:"afspreken; quedar bien = goed staan"}'),
  ('id:"cv76", es:"piel", nl:"huid; leer", tag:"cerv-lichaam", sl:"piel"}',
   'id:"cv76", es:"piel", nl:"huid", tag:"cerv-lichaam", sl:"piel", meer:"leer"}'),
  ('id:"cv79", es:"rico", nl:"rijk; lekker", tag:"cerv-eten", sl:"rico"}',
   'id:"cv79", es:"rico", nl:"rijk", tag:"cerv-eten", sl:"rico", meer:"lekker"}'),
  ('id:"cv80", es:"pesar", nl:"a pesar de = ondanks; wegen", tag:"cerv-winkelen", sl:"pesar"}',
   'id:"cv80", es:"pesar", nl:"wegen", tag:"cerv-winkelen", sl:"pesar", meer:"a pesar de = ondanks"}'),
  ('id:"cv96", es:"cerdo", nl:"varken; varkensvlees", tag:"cerv-economie", sl:"cerdo"}',
   'id:"cv96", es:"cerdo", nl:"varken", tag:"cerv-economie", sl:"cerdo", meer:"varkensvlees"}'),
  ('id:"cv97", es:"medicina", nl:"geneeskunde; medicijn", tag:"cerv-school", sl:"medicina"}',
   'id:"cv97", es:"medicina", nl:"geneeskunde", tag:"cerv-school", sl:"medicina", meer:"medicijn"}'),
  ('id:"cv99", es:"dedo", nl:"vinger; teen: dedo del pie", tag:"cerv-lichaam", sl:"dedo"}',
   'id:"cv99", es:"dedo", nl:"vinger", tag:"cerv-lichaam", sl:"dedo", meer:"teen: dedo del pie"}'),
  ('id:"cv101", es:"cuento", nl:"verhaal, sprookje; ik vertel", tag:"cerv-kunst", sl:"cuento"}',
   'id:"cv101", es:"cuento", nl:"verhaal, sprookje", tag:"cerv-kunst", sl:"cuento", meer:"ik vertel"}'),
  ('id:"cv106", es:"techo", nl:"plafond; dak", tag:"cerv-wonen", sl:"techo"}',
   'id:"cv106", es:"techo", nl:"plafond", tag:"cerv-wonen", sl:"techo", meer:"dak"}'),
  ('id:"cv107", es:"rosa", nl:"roze; roos; (naam Rosa)", tag:"cerv-natuur", sl:"rosa"}',
   'id:"cv107", es:"rosa", nl:"roze", tag:"cerv-natuur", sl:"rosa", meer:"roos; naam Rosa"}'),
  ('id:"cv113", es:"parecido", nl:"gelijkend; se parecen = ze lijken op elkaar", tag:"cerv-bestaan", sl:"parecido"}',
   'id:"cv113", es:"parecido", nl:"gelijkend", tag:"cerv-bestaan", sl:"parecido", meer:"se parecen = ze lijken op elkaar"}'),
  ('id:"cv115", es:"entrevista", nl:"interview; sollicitatiegesprek", tag:"cerv-media", sl:"entrevista"}',
   'id:"cv115", es:"entrevista", nl:"interview", tag:"cerv-media", sl:"entrevista", meer:"sollicitatiegesprek"}'),
  ('id:"cv119", es:"socio", nl:"zakenpartner, compagnon; lid", tag:"cerv-relaties", sl:"socio"}',
   'id:"cv119", es:"socio", nl:"zakenpartner, compagnon", tag:"cerv-relaties", sl:"socio", meer:"lid"}'),
  ('id:"cv120", es:"aburrido", nl:"saai; verveeld", tag:"cerv-oordeel", sl:"aburrido"}',
   'id:"cv120", es:"aburrido", nl:"saai", tag:"cerv-oordeel", sl:"aburrido", meer:"verveeld"}'),
  ('id:"cv129", es:"regla", nl:"regel; liniaal", tag:"cerv-school", sl:"regla"}',
   'id:"cv129", es:"regla", nl:"regel", tag:"cerv-school", sl:"regla", meer:"liniaal"}'),
  ('id:"cv138", es:"desierto", nl:"woestijn; verlaten", tag:"cerv-natuur", sl:"desierto"}',
   'id:"cv138", es:"desierto", nl:"woestijn", tag:"cerv-natuur", sl:"desierto", meer:"verlaten"}'),
  ('id:"cv142", es:"ponerse", nl:"aantrekken; worden", tag:"cerv-winkelen", sl:"ponerse"}',
   'id:"cv142", es:"ponerse", nl:"aantrekken", tag:"cerv-winkelen", sl:"ponerse", meer:"worden"}'),
  ('id:"cv144", es:"salsa", nl:"saus; salsa (dans!)", tag:"cerv-eten", sl:"salsa"}',
   'id:"cv144", es:"salsa", nl:"saus", tag:"cerv-eten", sl:"salsa", meer:"salsa (dans!)"}'),
  ('id:"cv145", es:"comercial", nl:"commercieel; reclamespot", tag:"cerv-werk", sl:"comercial"}',
   'id:"cv145", es:"comercial", nl:"commercieel", tag:"cerv-werk", sl:"comercial", meer:"reclamespot"}'),
  ('id:"cv146", es:"socorro", nl:"help!; hulp", tag:"cerv-diensten", sl:"socorro"}',
   'id:"cv146", es:"socorro", nl:"help!", tag:"cerv-diensten", sl:"socorro", meer:"hulp"}'),
  ('id:"cv148", es:"ron", nl:"rum; (naam Ron)", tag:"cerv-eten", sl:"ron"}',
   'id:"cv148", es:"ron", nl:"rum", tag:"cerv-eten", sl:"ron", meer:"naam Ron"}'),
  ('id:"cv149", es:"pasta", nl:"pasta; geld (Spanje, informeel)", tag:"cerv-eten", sl:"pasta"}',
   'id:"cv149", es:"pasta", nl:"pasta", tag:"cerv-eten", sl:"pasta", meer:"geld (Spanje, informeel)"}'),
  ('id:"cv150", es:"cristal", nl:"glas (materiaal); kristal", tag:"cerv-hoe", sl:"cristal"}',
   'id:"cv150", es:"cristal", nl:"glas (materiaal)", tag:"cerv-hoe", sl:"cristal", meer:"kristal"}'),
  ('id:"cv151", es:"fotografía", nl:"foto; fotografie", tag:"cerv-kunst", sl:"fotografia"}',
   'id:"cv151", es:"fotografía", nl:"foto", tag:"cerv-kunst", sl:"fotografia", meer:"fotografie"}'),
  ('id:"cv152", es:"anuncio", nl:"advertentie, reclame; aankondiging", tag:"cerv-economie", sl:"anuncio"}',
   'id:"cv152", es:"anuncio", nl:"advertentie, reclame", tag:"cerv-economie", sl:"anuncio", meer:"aankondiging"}'),
  ('id:"cv166", es:"tapa", nl:"deksel; tapa", tag:"cerv-eten", sl:"tapa"}',
   'id:"cv166", es:"tapa", nl:"deksel", tag:"cerv-eten", sl:"tapa", meer:"tapa"}'),
  ('id:"cv175", es:"suspender", nl:"zakken (voor een toets); opschorten", tag:"cerv-school", sl:"suspender"}',
   'id:"cv175", es:"suspender", nl:"zakken (voor een toets)", tag:"cerv-school", sl:"suspender", meer:"opschorten"}'),
  ('id:"cv198", es:"mandar", nl:"sturen; bevelen", tag:"cerv-media", sl:"mandar"}',
   'id:"cv198", es:"mandar", nl:"sturen", tag:"cerv-media", sl:"mandar", meer:"bevelen"}'),
  ('id:"cv200", es:"estrecho", nl:"smal, nauw; zeestraat", tag:"cerv-natuur", sl:"estrecho"}',
   'id:"cv200", es:"estrecho", nl:"smal, nauw", tag:"cerv-natuur", sl:"estrecho", meer:"zeestraat"}'),
  ('id:"cv207", es:"ancho", nl:"breed; breedte", tag:"cerv-hoeveel", sl:"ancho"}',
   'id:"cv207", es:"ancho", nl:"breed", tag:"cerv-hoeveel", sl:"ancho", meer:"breedte"}'),
  ('id:"cv211", es:"vamos", nl:"we gaan; kom op! (van ir)", tag:"cerv-wanneer", sl:"vamos"}',
   'id:"cv211", es:"vamos", nl:"we gaan", tag:"cerv-wanneer", sl:"vamos", meer:"kom op! (van ir)"}'),
  ('id:"cv214", es:"estado", nl:"geweest; staat, toestand", tag:"cerv-techniek", sl:"estado"}',
   'id:"cv214", es:"estado", nl:"geweest", tag:"cerv-techniek", sl:"estado", meer:"staat, toestand"}'),
  ('id:"cv216", es:"luego", nl:"daarna, straks; hasta luego = tot later", tag:"cerv-waar", sl:"luego"}',
   'id:"cv216", es:"luego", nl:"daarna, straks", tag:"cerv-waar", sl:"luego", meer:"hasta luego = tot later"}'),
  ('id:"cv219", es:"amor", nl:"liefde; schat", tag:"cerv-gevoel", sl:"amor"}',
   'id:"cv219", es:"amor", nl:"liefde", tag:"cerv-gevoel", sl:"amor", meer:"schat"}'),
  ('id:"cv220", es:"pasado", nl:"verleden; vorige", tag:"cerv-wanneer", sl:"pasado"}',
   'id:"cv220", es:"pasado", nl:"verleden", tag:"cerv-wanneer", sl:"pasado", meer:"vorige"}'),
  ('id:"cv225", es:"camino", nl:"weg, pad; onderweg", tag:"cerv-natuur", sl:"camino"}',
   'id:"cv225", es:"camino", nl:"weg, pad", tag:"cerv-natuur", sl:"camino", meer:"onderweg"}'),
  ('id:"cv226", es:"ayuda", nl:"hulp; help!", tag:"cerv-diensten", sl:"ayuda"}',
   'id:"cv226", es:"ayuda", nl:"hulp", tag:"cerv-diensten", sl:"ayuda", meer:"help!"}'),
  ('id:"cv227", es:"pasar", nl:"gebeuren; passeren; doorbrengen", tag:"cerv-gevoel", sl:"pasar"}',
   'id:"cv227", es:"pasar", nl:"gebeuren", tag:"cerv-gevoel", sl:"pasar", meer:"passeren; doorbrengen"}'),
  ('id:"cv229", es:"realidad", nl:"werkelijkheid; en realidad = eigenlijk", tag:"cerv-media", sl:"realidad"}',
   'id:"cv229", es:"realidad", nl:"werkelijkheid", tag:"cerv-media", sl:"realidad", meer:"en realidad = eigenlijk"}'),
  ('id:"cv231", es:"equipo", nl:"team, ploeg; uitrusting", tag:"cerv-vrije-tijd", sl:"equipo"}',
   'id:"cv231", es:"equipo", nl:"team, ploeg", tag:"cerv-vrije-tijd", sl:"equipo", meer:"uitrusting"}'),
  ('id:"cv235", es:"vuelta", nl:"rondje, terugkeer; dar una vuelta = een rondje lopen", tag:"cerv-winkelen", sl:"vuelta"}',
   'id:"cv235", es:"vuelta", nl:"rondje, terugkeer", tag:"cerv-winkelen", sl:"vuelta", meer:"dar una vuelta = een rondje lopen"}'),
  ('id:"cv236", es:"final", nl:"einde; al final = uiteindelijk", tag:"cerv-kunst", sl:"final"}',
   'id:"cv236", es:"final", nl:"einde", tag:"cerv-kunst", sl:"final", meer:"al final = uiteindelijk"}'),
  ('id:"cv239", es:"esperar", nl:"wachten; hopen; verwachten", tag:"cerv-denken", sl:"esperar"}',
   'id:"cv239", es:"esperar", nl:"wachten", tag:"cerv-denken", sl:"esperar", meer:"hopen; verwachten"}'),
  ('id:"cv243", es:"sitio", nl:"plek, plaats; website", tag:"cerv-natuur", sl:"sitio"}',
   'id:"cv243", es:"sitio", nl:"plek, plaats", tag:"cerv-natuur", sl:"sitio", meer:"website"}'),
  ('id:"cv245", es:"dado", nl:"gegeven (van dar); dobbelsteen", tag:"cerv-vrije-tijd", sl:"dado"}',
   'id:"cv245", es:"dado", nl:"gegeven (van dar)", tag:"cerv-vrije-tijd", sl:"dado", meer:"dobbelsteen"}'),
  ('id:"cv249", es:"real", nl:"echt; koninklijk", tag:"cerv-bestaan", sl:"real"}',
   'id:"cv249", es:"real", nl:"echt", tag:"cerv-bestaan", sl:"real", meer:"koninklijk"}'),
  ('id:"cv250", es:"orden", nl:"orde; bevel, opdracht", tag:"cerv-waar", sl:"orden"}',
   'id:"cv250", es:"orden", nl:"orde", tag:"cerv-waar", sl:"orden", meer:"bevel, opdracht"}'),
  ('id:"cv254", es:"extraño", nl:"vreemd, raar; ik mis", tag:"cerv-oordeel", sl:"extrano"}',
   'id:"cv254", es:"extraño", nl:"vreemd, raar", tag:"cerv-oordeel", sl:"extrano", meer:"ik mis"}'),
  ('id:"cv256", es:"general", nl:"algemeen; generaal", tag:"cerv-politiek", sl:"general"}',
   'id:"cv256", es:"general", nl:"algemeen", tag:"cerv-politiek", sl:"general", meer:"generaal"}'),
  ('id:"cv265", es:"compañía", nl:"bedrijf; gezelschap", tag:"cerv-media", sl:"compania"}',
   'id:"cv265", es:"compañía", nl:"bedrijf", tag:"cerv-media", sl:"compania", meer:"gezelschap"}'),
  ('id:"cv266", es:"vista", nl:"uitzicht; zicht; hasta la vista = tot ziens", tag:"cerv-gevoel", sl:"vista"}',
   'id:"cv266", es:"vista", nl:"uitzicht", tag:"cerv-gevoel", sl:"vista", meer:"zicht; hasta la vista = tot ziens"}'),
  ('id:"cv270", es:"carrera", nl:"carrière; race; studie", tag:"cerv-school", sl:"carrera"}',
   'id:"cv270", es:"carrera", nl:"carrière", tag:"cerv-school", sl:"carrera", meer:"race; studie"}'),
  ('id:"cv275", es:"dulce", nl:"zoet; snoepje", tag:"cerv-eten", sl:"dulce"}',
   'id:"cv275", es:"dulce", nl:"zoet", tag:"cerv-eten", sl:"dulce", meer:"snoepje"}'),
  ('id:"cv276", es:"principio", nl:"begin; principe; al principio = in het begin", tag:"cerv-techniek", sl:"principio"}',
   'id:"cv276", es:"principio", nl:"begin", tag:"cerv-techniek", sl:"principio", meer:"principe; al principio = in het begin"}'),
  ('id:"cv282", es:"mayoría", nl:"meerderheid; la mayoría de = de meeste", tag:"cerv-politiek", sl:"mayoria"}',
   'id:"cv282", es:"mayoría", nl:"meerderheid", tag:"cerv-politiek", sl:"mayoria", meer:"la mayoría de = de meeste"}'),
  ('id:"cv283", es:"vestido", nl:"jurk; gekleed", tag:"cerv-winkelen", sl:"vestido"}',
   'id:"cv283", es:"vestido", nl:"jurk", tag:"cerv-winkelen", sl:"vestido", meer:"gekleed"}'),
  ('id:"cv284", es:"corte", nl:"rechtbank; snit; knip", tag:"cerv-gezondheid", sl:"corte"}',
   'id:"cv284", es:"corte", nl:"rechtbank", tag:"cerv-gezondheid", sl:"corte", meer:"snit; knip"}'),
  ('id:"cv285", es:"duda", nl:"twijfel; sin duda = zonder twijfel", tag:"cerv-denken", sl:"duda"}',
   'id:"cv285", es:"duda", nl:"twijfel", tag:"cerv-denken", sl:"duda", meer:"sin duda = zonder twijfel"}'),
  ('id:"cv293", es:"partido", nl:"wedstrijd; (politieke) partij", tag:"cerv-vrije-tijd", sl:"partido"}',
   'id:"cv293", es:"partido", nl:"wedstrijd", tag:"cerv-vrije-tijd", sl:"partido", meer:"(politieke) partij"}'),
  ('id:"cv295", es:"san", nl:"Sint (San Juan = Sint Jan)", tag:"cerv-religie", sl:"san"}',
   'id:"cv295", es:"san", nl:"Sint", tag:"cerv-religie", sl:"san", meer:"San Juan = Sint Jan"}'),
  ('id:"cv298", es:"enfermo", nl:"ziek; zieke", tag:"cerv-gezondheid", sl:"enfermo"}',
   'id:"cv298", es:"enfermo", nl:"ziek", tag:"cerv-gezondheid", sl:"enfermo", meer:"zieke"}'),
  ('id:"cv299", es:"tratar", nl:"proberen; behandelen", tag:"cerv-wie-je-bent", sl:"tratar"}',
   'id:"cv299", es:"tratar", nl:"proberen", tag:"cerv-wie-je-bent", sl:"tratar", meer:"behandelen"}'),
  ('id:"cv300", es:"paciente", nl:"patiënt; geduldig", tag:"cerv-gezondheid", sl:"paciente"}',
   'id:"cv300", es:"paciente", nl:"patiënt", tag:"cerv-gezondheid", sl:"paciente", meer:"geduldig"}'),
  ('id:"cv301", es:"bolsa", nl:"tas, zak; beurs", tag:"cerv-winkelen", sl:"bolsa"}',
   'id:"cv301", es:"bolsa", nl:"tas, zak", tag:"cerv-winkelen", sl:"bolsa", meer:"beurs"}'),
  ('id:"cv302", es:"santo", nl:"heilig; heilige", tag:"cerv-relaties", sl:"santo"}',
   'id:"cv302", es:"santo", nl:"heilig", tag:"cerv-relaties", sl:"santo", meer:"heilige"}'),
  ('id:"cv304", es:"bomba", nl:"bom; pasarlo bomba = het geweldig hebben", tag:"cerv-politiek", sl:"bomba"}',
   'id:"cv304", es:"bomba", nl:"bom", tag:"cerv-politiek", sl:"bomba", meer:"pasarlo bomba = het geweldig hebben"}'),
  ('id:"cv307", es:"cuello", nl:"nek, hals; kraag", tag:"cerv-lichaam", sl:"cuello"}',
   'id:"cv307", es:"cuello", nl:"nek, hals", tag:"cerv-lichaam", sl:"cuello", meer:"kraag"}'),
  ('id:"cv312", es:"acabar", nl:"eindigen, afmaken; acabar de = net gedaan hebben", tag:"cerv-relaties", sl:"acabar"}',
   'id:"cv312", es:"acabar", nl:"eindigen, afmaken", tag:"cerv-relaties", sl:"acabar", meer:"acabar de = net gedaan hebben"}'),
  ('id:"cv316", es:"copa", nl:"glas (wijn); beker; tomar una copa = wat drinken", tag:"cerv-eten", sl:"copa"}',
   'id:"cv316", es:"copa", nl:"glas (wijn)", tag:"cerv-eten", sl:"copa", meer:"beker; tomar una copa = wat drinken"}'),
  ('id:"cv330", es:"total", nl:"totaal; kortom", tag:"cerv-bestaan", sl:"total"}',
   'id:"cv330", es:"total", nl:"totaal", tag:"cerv-bestaan", sl:"total", meer:"kortom"}'),
  ('id:"cv348", es:"herida", nl:"wond; gewond (v)", tag:"cerv-gezondheid", sl:"herida"}',
   'id:"cv348", es:"herida", nl:"wond", tag:"cerv-gezondheid", sl:"herida", meer:"gewond (v)"}'),
  ('id:"cv350", es:"peso", nl:"gewicht; peso (munt); ik weeg", tag:"cerv-hoeveel", sl:"peso"}',
   'id:"cv350", es:"peso", nl:"gewicht", tag:"cerv-hoeveel", sl:"peso", meer:"peso (munt); ik weeg"}'),
  ('id:"cv360", es:"interés", nl:"belang; interesse; rente", tag:"cerv-oordeel", sl:"interes"}',
   'id:"cv360", es:"interés", nl:"belang", tag:"cerv-oordeel", sl:"interes", meer:"interesse; rente"}'),
  ('id:"cv362", es:"escenario", nl:"podium; scenario", tag:"cerv-vrije-tijd", sl:"escenario"}',
   'id:"cv362", es:"escenario", nl:"podium", tag:"cerv-vrije-tijd", sl:"escenario", meer:"scenario"}'),
  ('id:"cv363", es:"diario", nl:"dagboek; krant; dagelijks", tag:"cerv-wie-je-bent", sl:"diario"}',
   'id:"cv363", es:"diario", nl:"dagboek", tag:"cerv-wie-je-bent", sl:"diario", meer:"krant; dagelijks"}'),
  ('id:"cv380", es:"firma", nl:"handtekening; bedrijf; onderteken!", tag:"cerv-media", sl:"firma"}',
   'id:"cv380", es:"firma", nl:"handtekening", tag:"cerv-media", sl:"firma", meer:"bedrijf; onderteken!"}'),
  ('id:"cv385", es:"pintura", nl:"schilderij; verf; schilderkunst", tag:"cerv-wonen", sl:"pintura"}',
   'id:"cv385", es:"pintura", nl:"schilderij", tag:"cerv-wonen", sl:"pintura", meer:"verf; schilderkunst"}'),
  ('id:"cv387", es:"clara", nl:"duidelijk, helder (v); eiwit", tag:"cerv-eten", sl:"clara"}',
   'id:"cv387", es:"clara", nl:"duidelijk, helder (v)", tag:"cerv-eten", sl:"clara", meer:"eiwit"}'),
  ('id:"cv388", es:"mundial", nl:"wereld-; WK: el Mundial", tag:"cerv-natuur", sl:"mundial"}',
   'id:"cv388", es:"mundial", nl:"wereld-", tag:"cerv-natuur", sl:"mundial", meer:"WK: el Mundial"}'),
  ('id:"cv389", es:"notas", nl:"cijfers; notities; jij merkt", tag:"cerv-school", sl:"notas"}',
   'id:"cv389", es:"notas", nl:"cijfers", tag:"cerv-school", sl:"notas", meer:"notities; jij merkt"}'),
  ('id:"cv395", es:"tirar", nl:"gooien, weggooien; trekken", tag:"cerv-winkelen", sl:"tirar"}',
   'id:"cv395", es:"tirar", nl:"gooien, weggooien", tag:"cerv-winkelen", sl:"tirar", meer:"trekken"}'),
  ('id:"cv396", es:"carro", nl:"auto (Lat-Am); kar", tag:"cerv-winkelen", sl:"carro"}',
   'id:"cv396", es:"carro", nl:"auto (Lat-Am)", tag:"cerv-winkelen", sl:"carro", meer:"kar"}'),
  ('id:"cv397", es:"venta", nl:"verkoop; en venta = te koop", tag:"cerv-economie", sl:"venta"}',
   'id:"cv397", es:"venta", nl:"verkoop", tag:"cerv-economie", sl:"venta", meer:"en venta = te koop"}'),
  ('id:"cv398", es:"hacerse", nl:"worden; zich laten...", tag:"cerv-vrije-tijd", sl:"hacerse"}',
   'id:"cv398", es:"hacerse", nl:"worden", tag:"cerv-vrije-tijd", sl:"hacerse", meer:"zich laten..."}'),
  ('id:"cv400", es:"cadena", nl:"ketting; keten; tv-zender", tag:"cerv-wie-je-bent", sl:"cadena"}',
   'id:"cv400", es:"cadena", nl:"ketting", tag:"cerv-wie-je-bent", sl:"cadena", meer:"keten; tv-zender"}'),
  ('id:"cv402", es:"plata", nl:"zilver; geld (Lat-Am)", tag:"cerv-techniek", sl:"plata"}',
   'id:"cv402", es:"plata", nl:"zilver", tag:"cerv-techniek", sl:"plata", meer:"geld (Lat-Am)"}'),
  ('id:"cv404", es:"compra", nl:"aankoop; koop!", tag:"cerv-wonen", sl:"compra"}',
   'id:"cv404", es:"compra", nl:"aankoop", tag:"cerv-wonen", sl:"compra", meer:"koop!"}'),
  ('id:"cv405", es:"tráfico", nl:"verkeer; handel", tag:"cerv-reizen", sl:"trafico"}',
   'id:"cv405", es:"tráfico", nl:"verkeer", tag:"cerv-reizen", sl:"trafico", meer:"handel"}'),
  ('id:"cv407", es:"arena", nl:"zand; arena", tag:"cerv-reizen", sl:"arena"}',
   'id:"cv407", es:"arena", nl:"zand", tag:"cerv-reizen", sl:"arena", meer:"arena"}'),
  ('id:"cv416", es:"servir", nl:"dienen; serveren; para servirle = tot uw dienst", tag:"cerv-eten", sl:"servir"}',
   'id:"cv416", es:"servir", nl:"dienen", tag:"cerv-eten", sl:"servir", meer:"serveren; para servirle = tot uw dienst"}'),
  ('id:"cv418", es:"muñeca", nl:"pols; pop", tag:"cerv-lichaam", sl:"muneca"}',
   'id:"cv418", es:"muñeca", nl:"pols", tag:"cerv-lichaam", sl:"muneca", meer:"pop"}'),
  ('id:"cv430", es:"exterior", nl:"buitenkant; buitenland", tag:"cerv-waar", sl:"exterior"}',
   'id:"cv430", es:"exterior", nl:"buitenkant", tag:"cerv-waar", sl:"exterior", meer:"buitenland"}'),
  ('id:"cv431", es:"ambiente", nl:"sfeer; omgeving; medio ambiente = milieu", tag:"cerv-wonen", sl:"ambiente"}',
   'id:"cv431", es:"ambiente", nl:"sfeer", tag:"cerv-wonen", sl:"ambiente", meer:"omgeving; medio ambiente = milieu"}'),
  ('id:"cv434", es:"hierba", nl:"gras; kruid", tag:"cerv-natuur", sl:"hierba"}',
   'id:"cv434", es:"hierba", nl:"gras", tag:"cerv-natuur", sl:"hierba", meer:"kruid"}'),
  ('id:"cv438", es:"física", nl:"natuurkunde; fysiek (v)", tag:"cerv-techniek", sl:"fisica"}',
   'id:"cv438", es:"física", nl:"natuurkunde", tag:"cerv-techniek", sl:"fisica", meer:"fysiek (v)"}'),
  ('id:"cv444", es:"conferencia", nl:"conferentie; lezing", tag:"cerv-school", sl:"conferencia"}',
   'id:"cv444", es:"conferencia", nl:"conferentie", tag:"cerv-school", sl:"conferencia", meer:"lezing"}'),
  ('id:"cv458", es:"yema", nl:"eigeel; knop", tag:"cerv-eten", sl:"yema"}',
   'id:"cv458", es:"yema", nl:"eigeel", tag:"cerv-eten", sl:"yema", meer:"knop"}'),
  ('id:"cv468", es:"obra", nl:"werk; bouwplaats", tag:"cerv-kunst", sl:"obra"}',
   'id:"cv468", es:"obra", nl:"werk", tag:"cerv-kunst", sl:"obra", meer:"bouwplaats"}'),
  ('id:"cv469", es:"portero", nl:"portier; keeper", tag:"cerv-wonen", sl:"portero"}',
   'id:"cv469", es:"portero", nl:"portier", tag:"cerv-wonen", sl:"portero", meer:"keeper"}'),
  ('id:"cv477", es:"ingresar", nl:"opnemen (in ziekenhuis); storten", tag:"cerv-diensten", sl:"ingresar"}',
   'id:"cv477", es:"ingresar", nl:"opnemen (in ziekenhuis)", tag:"cerv-diensten", sl:"ingresar", meer:"storten"}'),
  ('id:"cv492", es:"matrícula", nl:"kentekenplaat; inschrijving", tag:"cerv-school", sl:"matricula"}',
   'id:"cv492", es:"matrícula", nl:"kentekenplaat", tag:"cerv-school", sl:"matricula", meer:"inschrijving"}'),
  ('id:"cv500", es:"vía", nl:"spoor; weg", tag:"cerv-reizen", sl:"via"}',
   'id:"cv500", es:"vía", nl:"spoor", tag:"cerv-reizen", sl:"via", meer:"weg"}'),
  ('id:"cv507", es:"comercio", nl:"handel; winkel", tag:"cerv-winkelen", sl:"comercio"}',
   'id:"cv507", es:"comercio", nl:"handel", tag:"cerv-winkelen", sl:"comercio", meer:"winkel"}'),
  ('id:"cv509", es:"despedir", nl:"ontslaan; uitzwaaien", tag:"cerv-werk", sl:"despedir"}',
   'id:"cv509", es:"despedir", nl:"ontslaan", tag:"cerv-werk", sl:"despedir", meer:"uitzwaaien"}'),
  ('id:"cv532", es:"collar", nl:"halsketting; halsband", tag:"cerv-wie-je-bent", sl:"collar"}',
   'id:"cv532", es:"collar", nl:"halsketting", tag:"cerv-wie-je-bent", sl:"collar", meer:"halsband"}'),
  ('id:"cv549", es:"pesado", nl:"vervelend, opdringerig; zwaar", tag:"cerv-hoeveel", sl:"pesado"}',
   'id:"cv549", es:"pesado", nl:"vervelend, opdringerig", tag:"cerv-hoeveel", sl:"pesado", meer:"zwaar"}'),
  ('id:"cv553", es:"atender", nl:"helpen, bedienen; opletten", tag:"cerv-eten", sl:"atender"}',
   'id:"cv553", es:"atender", nl:"helpen, bedienen", tag:"cerv-eten", sl:"atender", meer:"opletten"}'),
  ('id:"cv572", es:"batería", nl:"drums; accu", tag:"cerv-media", sl:"bateria"}',
   'id:"cv572", es:"batería", nl:"drums", tag:"cerv-media", sl:"bateria", meer:"accu"}'),
  ('id:"cv588", es:"demanda", nl:"aanklacht; vraag (markt)", tag:"cerv-werk", sl:"demanda"}',
   'id:"cv588", es:"demanda", nl:"aanklacht", tag:"cerv-werk", sl:"demanda", meer:"vraag (markt)"}'),
  ('id:"cv594", es:"población", nl:"bevolking; plaats", tag:"cerv-natuur", sl:"poblacion"}',
   'id:"cv594", es:"población", nl:"bevolking", tag:"cerv-natuur", sl:"poblacion", meer:"plaats"}'),
  ('id:"cv603", es:"como", nl:"zoals, als; ik eet", tag:"cerv-hoeveel", sl:"como"}',
   'id:"cv603", es:"como", nl:"zoals, als", tag:"cerv-hoeveel", sl:"como", meer:"ik eet"}'),
  ('id:"cv604", es:"verdad", nl:"waarheid; toch?", tag:"cerv-denken", sl:"verdad"}',
   'id:"cv604", es:"verdad", nl:"waarheid", tag:"cerv-denken", sl:"verdad", meer:"toch?"}'),
  ('id:"cv605", es:"tiempo", nl:"tijd; weer", tag:"cerv-natuur", sl:"tiempo"}',
   'id:"cv605", es:"tiempo", nl:"tijd", tag:"cerv-natuur", sl:"tiempo", meer:"weer"}'),
  ('id:"cv609", es:"razón", nl:"gelijk; reden; tener razón = gelijk hebben", tag:"cerv-religie", sl:"razon"}',
   'id:"cv609", es:"razón", nl:"gelijk", tag:"cerv-religie", sl:"razon", meer:"reden; tener razón = gelijk hebben"}'),
  ('id:"cv610", es:"cierto", nl:"waar, zeker; por cierto = trouwens", tag:"cerv-bestaan", sl:"cierto"}',
   'id:"cv610", es:"cierto", nl:"waar, zeker", tag:"cerv-bestaan", sl:"cierto", meer:"por cierto = trouwens"}'),
  ('id:"cv616", es:"justo", nl:"precies, net; rechtvaardig", tag:"cerv-gevoel", sl:"justo"}',
   'id:"cv616", es:"justo", nl:"precies, net", tag:"cerv-gevoel", sl:"justo", meer:"rechtvaardig"}'),
  ('id:"cv619", es:"cuidado", nl:"voorzichtig!; zorg", tag:"cerv-relaties", sl:"cuidado"}',
   'id:"cv619", es:"cuidado", nl:"voorzichtig!", tag:"cerv-relaties", sl:"cuidado", meer:"zorg"}'),
  ('id:"cv622", es:"perdón", nl:"sorry, pardon; vergeving", tag:"cerv-politiek", sl:"perdon"}',
   'id:"cv622", es:"perdón", nl:"sorry, pardon", tag:"cerv-politiek", sl:"perdon", meer:"vergeving"}'),
  ('id:"cv623", es:"falta", nl:"gebrek; hace falta = het is nodig", tag:"cerv-oordeel", sl:"falta"}',
   'id:"cv623", es:"falta", nl:"gebrek", tag:"cerv-oordeel", sl:"falta", meer:"hace falta = het is nodig"}'),
  ('id:"cv624", es:"prueba", nl:"bewijs; test, proef", tag:"cerv-school", sl:"prueba"}',
   'id:"cv624", es:"prueba", nl:"bewijs", tag:"cerv-school", sl:"prueba", meer:"test, proef"}'),
  ('id:"cv627", es:"odio", nl:"ik haat; haat", tag:"cerv-gevoel", sl:"odio"}',
   'id:"cv627", es:"odio", nl:"ik haat", tag:"cerv-gevoel", sl:"odio", meer:"haat"}'),
  ('id:"cv628", es:"frente", nl:"voorhoofd; front; frente a = tegenover", tag:"cerv-lichaam", sl:"frente"}',
   'id:"cv628", es:"frente", nl:"voorhoofd", tag:"cerv-lichaam", sl:"frente", meer:"front; frente a = tegenover"}'),
  ('id:"cv632", es:"gusto", nl:"smaak; mucho gusto = aangenaam", tag:"cerv-gevoel", sl:"gusto"}',
   'id:"cv632", es:"gusto", nl:"smaak", tag:"cerv-gevoel", sl:"gusto", meer:"mucho gusto = aangenaam"}'),
  ('id:"cv638", es:"servicio", nl:"dienst, service; toilet", tag:"cerv-diensten", sl:"servicio"}',
   'id:"cv638", es:"servicio", nl:"dienst, service", tag:"cerv-diensten", sl:"servicio", meer:"toilet"}'),
  ('id:"cv639", es:"cámara", nl:"camera; kamer", tag:"cerv-media", sl:"camara"}',
   'id:"cv639", es:"cámara", nl:"camera", tag:"cerv-media", sl:"camara", meer:"kamer"}'),
  ('id:"cv645", es:"permiso", nl:"toestemming; con permiso = pardon", tag:"cerv-reizen", sl:"permiso"}',
   'id:"cv645", es:"permiso", nl:"toestemming", tag:"cerv-reizen", sl:"permiso", meer:"con permiso = pardon"}'),
  ('id:"cv653", es:"cargo", nl:"functie; hacerse cargo = zich ontfermen over", tag:"cerv-economie", sl:"cargo"}',
   'id:"cv653", es:"cargo", nl:"functie", tag:"cerv-economie", sl:"cargo", meer:"hacerse cargo = zich ontfermen over"}'),
  ('id:"cv656", es:"destino", nl:"bestemming; lot", tag:"cerv-waar", sl:"destino"}',
   'id:"cv656", es:"destino", nl:"bestemming", tag:"cerv-waar", sl:"destino", meer:"lot"}'),
  ('id:"cv657", es:"juicio", nl:"rechtszaak; oordeel", tag:"cerv-politiek", sl:"juicio"}',
   'id:"cv657", es:"juicio", nl:"rechtszaak", tag:"cerv-politiek", sl:"juicio", meer:"oordeel"}'),
  ('id:"cv658", es:"equivocado", nl:"fout, verkeerd; estar equivocado = het mis hebben", tag:"cerv-oordeel", sl:"equivocado"}',
   'id:"cv658", es:"equivocado", nl:"fout, verkeerd", tag:"cerv-oordeel", sl:"equivocado", meer:"estar equivocado = het mis hebben"}'),
  ('id:"cv661", es:"especie", nl:"soort; una especie de = een soort van", tag:"cerv-techniek", sl:"especie"}',
   'id:"cv661", es:"especie", nl:"soort", tag:"cerv-techniek", sl:"especie", meer:"una especie de = een soort van"}'),
  ('id:"cv663", es:"fondo", nl:"bodem, achtergrond; en el fondo = eigenlijk", tag:"cerv-kunst", sl:"fondo"}',
   'id:"cv663", es:"fondo", nl:"bodem, achtergrond", tag:"cerv-kunst", sl:"fondo", meer:"en el fondo = eigenlijk"}'),
  ('id:"cv664", es:"pista", nl:"spoor, aanwijzing; baan", tag:"cerv-vrije-tijd", sl:"pista"}',
   'id:"cv664", es:"pista", nl:"spoor, aanwijzing", tag:"cerv-vrije-tijd", sl:"pista", meer:"baan"}'),
  ('id:"cv666", es:"banda", nl:"band; bende", tag:"cerv-diensten", sl:"banda"}',
   'id:"cv666", es:"banda", nl:"band", tag:"cerv-diensten", sl:"banda", meer:"bende"}'),
  ('id:"cv667", es:"culpable", nl:"schuldig; schuldige", tag:"cerv-politiek", sl:"culpable"}',
   'id:"cv667", es:"culpable", nl:"schuldig", tag:"cerv-politiek", sl:"culpable", meer:"schuldige"}'),
  ('id:"cv672", es:"marcha", nl:"vertrek; versnelling; en marcha = onderweg", tag:"cerv-relaties", sl:"marcha"}',
   'id:"cv672", es:"marcha", nl:"vertrek", tag:"cerv-relaties", sl:"marcha", meer:"versnelling; en marcha = onderweg"}'),
  ('id:"cv674", es:"nota", nl:"cijfer (school); notitie; noot", tag:"cerv-school", sl:"nota"}',
   'id:"cv674", es:"nota", nl:"cijfer (school)", tag:"cerv-school", sl:"nota", meer:"notitie; noot"}'),
  ('id:"cv675", es:"valor", nl:"moed; waarde", tag:"cerv-economie", sl:"valor"}',
   'id:"cv675", es:"valor", nl:"moed", tag:"cerv-economie", sl:"valor", meer:"waarde"}'),
  ('id:"cv680", es:"pedido", nl:"bestelling; gevraagd (van pedir)", tag:"cerv-economie", sl:"pedido"}',
   'id:"cv680", es:"pedido", nl:"bestelling", tag:"cerv-economie", sl:"pedido", meer:"gevraagd (van pedir)"}'),
  ('id:"cv683", es:"ganado", nl:"gewonnen (van ganar); vee", tag:"cerv-economie", sl:"ganado"}',
   'id:"cv683", es:"ganado", nl:"gewonnen (van ganar)", tag:"cerv-economie", sl:"ganado", meer:"vee"}'),
  ('id:"cv689", es:"partir", nl:"vertrekken; a partir de = vanaf", tag:"cerv-waar", sl:"partir"}',
   'id:"cv689", es:"partir", nl:"vertrekken", tag:"cerv-waar", sl:"partir", meer:"a partir de = vanaf"}'),
  ('id:"cv691", es:"muestra", nl:"voorbeeld, staal; laat zien! (van mostrar)", tag:"cerv-vrije-tijd", sl:"muestra"}',
   'id:"cv691", es:"muestra", nl:"voorbeeld, staal", tag:"cerv-vrije-tijd", sl:"muestra", meer:"laat zien! (van mostrar)"}'),
  ('id:"cv699", es:"cabo", nl:"al fin y al cabo = uiteindelijk; kaap; korporaal", tag:"cerv-natuur", sl:"cabo"}',
   'id:"cv699", es:"cabo", nl:"kaap", tag:"cerv-natuur", sl:"cabo", meer:"korporaal; al fin y al cabo = uiteindelijk"}'),
  ('id:"cv700", es:"sospechoso", nl:"verdacht; verdachte", tag:"cerv-diensten", sl:"sospechoso"}',
   'id:"cv700", es:"sospechoso", nl:"verdacht", tag:"cerv-diensten", sl:"sospechoso", meer:"verdachte"}'),
  ('id:"cv703", es:"familiar", nl:"familielid; vertrouwd", tag:"cerv-relaties", sl:"familiar"}',
   'id:"cv703", es:"familiar", nl:"familielid", tag:"cerv-relaties", sl:"familiar", meer:"vertrouwd"}'),
  ('id:"cv709", es:"puente", nl:"brug; lang weekend", tag:"cerv-reizen", sl:"puente"}',
   'id:"cv709", es:"puente", nl:"brug", tag:"cerv-reizen", sl:"puente", meer:"lang weekend"}'),
  ('id:"cv710", es:"echar", nl:"gooien; echar de menos = missen", tag:"cerv-vrije-tijd", sl:"echar"}',
   'id:"cv710", es:"echar", nl:"gooien", tag:"cerv-vrije-tijd", sl:"echar", meer:"echar de menos = missen"}'),
  ('id:"cv715", es:"carga", nl:"lading, last; laad!", tag:"cerv-hoeveel", sl:"carga"}',
   'id:"cv715", es:"carga", nl:"lading, last", tag:"cerv-hoeveel", sl:"carga", meer:"laad!"}'),
  ('id:"cv716", es:"presente", nl:"aanwezig; heden; cadeau", tag:"cerv-bestaan", sl:"presente"}',
   'id:"cv716", es:"presente", nl:"aanwezig", tag:"cerv-bestaan", sl:"presente", meer:"heden; cadeau"}'),
  ('id:"cv717", es:"uso", nl:"gebruik; ik gebruik", tag:"cerv-oordeel", sl:"uso"}',
   'id:"cv717", es:"uso", nl:"gebruik", tag:"cerv-oordeel", sl:"uso", meer:"ik gebruik"}'),
  ('id:"cv718", es:"profesional", nl:"professioneel; vakman", tag:"cerv-werk", sl:"profesional"}',
   'id:"cv718", es:"profesional", nl:"professioneel", tag:"cerv-werk", sl:"profesional", meer:"vakman"}'),
  ('id:"cv720", es:"leo", nl:"ik lees (van leer); (naam Leo)", tag:"cerv-natuur", sl:"leo"}',
   'id:"cv720", es:"leo", nl:"ik lees (van leer)", tag:"cerv-natuur", sl:"leo", meer:"naam Leo"}'),
  ('id:"cv721", es:"central", nl:"centraal; centrale", tag:"cerv-waar", sl:"central"}',
   'id:"cv721", es:"central", nl:"centraal", tag:"cerv-waar", sl:"central", meer:"centrale"}'),
  ('id:"cv724", es:"fiscal", nl:"officier van justitie; fiscaal", tag:"cerv-politiek", sl:"fiscal"}',
   'id:"cv724", es:"fiscal", nl:"officier van justitie", tag:"cerv-politiek", sl:"fiscal", meer:"fiscaal"}'),
  ('id:"cv725", es:"amenaza", nl:"dreiging; hij/zij dreigt", tag:"cerv-denken", sl:"amenaza"}',
   'id:"cv725", es:"amenaza", nl:"dreiging", tag:"cerv-denken", sl:"amenaza", meer:"hij/zij dreigt"}'),
  ('id:"cv728", es:"correo", nl:"post; e-mail", tag:"cerv-diensten", sl:"correo"}',
   'id:"cv728", es:"correo", nl:"post", tag:"cerv-diensten", sl:"correo", meer:"e-mail"}'),
  ('id:"cv730", es:"local", nl:"lokaal; zaak, pand", tag:"cerv-natuur", sl:"local"}',
   'id:"cv730", es:"local", nl:"lokaal", tag:"cerv-natuur", sl:"local", meer:"zaak, pand"}'),
  ('id:"cv731", es:"pago", nl:"betaling; ik betaal", tag:"cerv-diensten", sl:"pago"}',
   'id:"cv731", es:"pago", nl:"betaling", tag:"cerv-diensten", sl:"pago", meer:"ik betaal"}'),
  ('id:"cv732", es:"comienzo", nl:"begin; ik begin", tag:"cerv-wanneer", sl:"comienzo"}',
   'id:"cv732", es:"comienzo", nl:"begin", tag:"cerv-wanneer", sl:"comienzo", meer:"ik begin"}'),
  ('id:"cv735", es:"aspecto", nl:"uiterlijk; aspect", tag:"cerv-lichaam", sl:"aspecto"}',
   'id:"cv735", es:"aspecto", nl:"uiterlijk", tag:"cerv-lichaam", sl:"aspecto", meer:"aspect"}'),
  ('id:"cv737", es:"fuente", nl:"bron; fontein; schaal", tag:"cerv-eten", sl:"fuente"}',
   'id:"cv737", es:"fuente", nl:"bron", tag:"cerv-eten", sl:"fuente", meer:"fontein; schaal"}'),
  ('id:"cv739", es:"deber", nl:"moeten; plicht; huiswerk: deberes", tag:"cerv-diensten", sl:"deber"}',
   'id:"cv739", es:"deber", nl:"moeten", tag:"cerv-diensten", sl:"deber", meer:"plicht; huiswerk: deberes"}'),
  ('id:"cv742", es:"manejar", nl:"besturen; rijden (Lat-Am); hanteren", tag:"cerv-media", sl:"manejar"}',
   'id:"cv742", es:"manejar", nl:"besturen", tag:"cerv-media", sl:"manejar", meer:"rijden (Lat-Am); hanteren"}'),
  ('id:"cv743", es:"acto", nl:"daad; akte; en el acto = ter plekke", tag:"cerv-relaties", sl:"acto"}',
   'id:"cv743", es:"acto", nl:"daad", tag:"cerv-relaties", sl:"acto", meer:"akte; en el acto = ter plekke"}'),
  ('id:"cv744", es:"inútil", nl:"nutteloos; nietsnut", tag:"cerv-oordeel", sl:"inutil"}',
   'id:"cv744", es:"inútil", nl:"nutteloos", tag:"cerv-oordeel", sl:"inutil", meer:"nietsnut"}'),
  ('id:"cv746", es:"detener", nl:"stoppen; aanhouden, arresteren", tag:"cerv-diensten", sl:"detener"}',
   'id:"cv746", es:"detener", nl:"stoppen", tag:"cerv-diensten", sl:"detener", meer:"aanhouden, arresteren"}'),
  ('id:"cv748", es:"invitado", nl:"gast; uitgenodigd", tag:"cerv-relaties", sl:"invitado"}',
   'id:"cv748", es:"invitado", nl:"gast", tag:"cerv-relaties", sl:"invitado", meer:"uitgenodigd"}'),
  ('id:"cv753", es:"criminal", nl:"misdadiger; misdadig", tag:"cerv-politiek", sl:"criminal"}',
   'id:"cv753", es:"criminal", nl:"misdadiger", tag:"cerv-politiek", sl:"criminal", meer:"misdadig"}'),
  ('id:"cv755", es:"crédito", nl:"krediet; tarjeta de crédito = creditcard", tag:"cerv-diensten", sl:"credito"}',
   'id:"cv755", es:"crédito", nl:"krediet", tag:"cerv-diensten", sl:"credito", meer:"tarjeta de crédito = creditcard"}'),
  ('id:"cv757", es:"recién", nl:"net, pas; recién nacido = pasgeboren", tag:"cerv-hoe", sl:"recien"}',
   'id:"cv757", es:"recién", nl:"net, pas", tag:"cerv-hoe", sl:"recien", meer:"recién nacido = pasgeboren"}'),
  ('id:"cv758", es:"visión", nl:"visie; zicht; visioen", tag:"cerv-hoe", sl:"vision"}',
   'id:"cv758", es:"visión", nl:"visie", tag:"cerv-hoe", sl:"vision", meer:"zicht; visioen"}'),
  ('id:"cv759", es:"curso", nl:"cursus; schooljaar", tag:"cerv-school", sl:"curso"}',
   'id:"cv759", es:"curso", nl:"cursus", tag:"cerv-school", sl:"curso", meer:"schooljaar"}'),
  ('id:"cv762", es:"cura", nl:"priester; genezing; hij/zij geneest", tag:"cerv-religie", sl:"cura"}',
   'id:"cv762", es:"cura", nl:"priester", tag:"cerv-religie", sl:"cura", meer:"genezing; hij/zij geneest"}'),
  ('id:"cv764", es:"inteligencia", nl:"intelligentie; inlichtingendienst", tag:"cerv-denken", sl:"inteligencia"}',
   'id:"cv764", es:"inteligencia", nl:"intelligentie", tag:"cerv-denken", sl:"inteligencia", meer:"inlichtingendienst"}'),
  ('id:"cv765", es:"helado", nl:"ijsje; ijskoud", tag:"cerv-eten", sl:"helado"}',
   'id:"cv765", es:"helado", nl:"ijsje", tag:"cerv-eten", sl:"helado", meer:"ijskoud"}'),
  ('id:"cv775", es:"bravo", nl:"bravo; woest", tag:"cerv-natuur", sl:"bravo"}',
   'id:"cv775", es:"bravo", nl:"bravo", tag:"cerv-natuur", sl:"bravo", meer:"woest"}'),
  ('id:"cv778", es:"corriente", nl:"stroom, stroming; gewoon", tag:"cerv-natuur", sl:"corriente"}',
   'id:"cv778", es:"corriente", nl:"stroom, stroming", tag:"cerv-natuur", sl:"corriente", meer:"gewoon"}'),
  ('id:"cv779", es:"mono", nl:"aap; schattig; overall", tag:"cerv-werk", sl:"mono"}',
   'id:"cv779", es:"mono", nl:"aap", tag:"cerv-werk", sl:"mono", meer:"schattig; overall"}'),
  ('id:"cv782", es:"compromiso", nl:"verplichting; verloving; compromis", tag:"cerv-politiek", sl:"compromiso"}',
   'id:"cv782", es:"compromiso", nl:"verplichting", tag:"cerv-politiek", sl:"compromiso", meer:"verloving; compromis"}'),
  ('id:"cv784", es:"cobarde", nl:"lafaard; laf", tag:"cerv-gevoel", sl:"cobarde"}',
   'id:"cv784", es:"cobarde", nl:"lafaard", tag:"cerv-gevoel", sl:"cobarde", meer:"laf"}'),
  ('id:"cv785", es:"firme", nl:"stevig, vastberaden; teken! (van firmar)", tag:"cerv-reizen", sl:"firme"}',
   'id:"cv785", es:"firme", nl:"stevig, vastberaden", tag:"cerv-reizen", sl:"firme", meer:"teken! (van firmar)"}'),
  ('id:"cv789", es:"cumplir", nl:"nakomen; jarig zijn: cumplir años", tag:"cerv-gevoel", sl:"cumplir"}',
   'id:"cv789", es:"cumplir", nl:"nakomen", tag:"cerv-gevoel", sl:"cumplir", meer:"jarig zijn: cumplir años"}'),
  ('id:"cv790", es:"usado", nl:"gebruikt; tweedehands", tag:"cerv-hoe", sl:"usado"}',
   'id:"cv790", es:"usado", nl:"gebruikt", tag:"cerv-hoe", sl:"usado", meer:"tweedehands"}'),
  ('id:"cv796", es:"particular", nl:"bijzonder; privé; en particular = in het bijzonder", tag:"cerv-bestaan", sl:"particular"}',
   'id:"cv796", es:"particular", nl:"bijzonder", tag:"cerv-bestaan", sl:"particular", meer:"privé; en particular = in het bijzonder"}'),
  ('id:"cv809", es:"casualidad", nl:"toeval; por casualidad = toevallig", tag:"cerv-bestaan", sl:"casualidad"}',
   'id:"cv809", es:"casualidad", nl:"toeval", tag:"cerv-bestaan", sl:"casualidad", meer:"por casualidad = toevallig"}'),
  ('id:"cv810", es:"dulces", nl:"snoep; zoet (mv)", tag:"cerv-eten", sl:"dulces"}',
   'id:"cv810", es:"dulces", nl:"snoep", tag:"cerv-eten", sl:"dulces", meer:"zoet (mv)"}'),
  ('id:"cv812", es:"entrega", nl:"levering; overhandiging; lever in!", tag:"cerv-diensten", sl:"entrega"}',
   'id:"cv812", es:"entrega", nl:"levering", tag:"cerv-diensten", sl:"entrega", meer:"overhandiging; lever in!"}'),
  ('id:"cv813", es:"voto", nl:"stem; ik stem", tag:"cerv-politiek", sl:"voto"}',
   'id:"cv813", es:"voto", nl:"stem", tag:"cerv-politiek", sl:"voto", meer:"ik stem"}'),
  ('id:"cv815", es:"fresco", nl:"fris, koel; brutaal", tag:"cerv-kunst", sl:"fresco"}',
   'id:"cv815", es:"fresco", nl:"fris, koel", tag:"cerv-kunst", sl:"fresco", meer:"brutaal"}'),
  ('id:"cv817", es:"ciego", nl:"blind; blinde", tag:"cerv-lichaam", sl:"ciego"}',
   'id:"cv817", es:"ciego", nl:"blind", tag:"cerv-lichaam", sl:"ciego", meer:"blinde"}'),
  ('id:"cv820", es:"estudios", nl:"studies; studio\'s", tag:"cerv-school", sl:"estudios"}',
   'id:"cv820", es:"estudios", nl:"studies", tag:"cerv-school", sl:"estudios", meer:"studio\'s"}'),
  ('id:"cv821", es:"competencia", nl:"concurrentie; wedstrijd (Lat-Am)", tag:"cerv-economie", sl:"competencia"}',
   'id:"cv821", es:"competencia", nl:"concurrentie", tag:"cerv-economie", sl:"competencia", meer:"wedstrijd (Lat-Am)"}'),
  ('id:"cv829", es:"curioso", nl:"nieuwsgierig; merkwaardig", tag:"cerv-gevoel", sl:"curioso"}',
   'id:"cv829", es:"curioso", nl:"nieuwsgierig", tag:"cerv-gevoel", sl:"curioso", meer:"merkwaardig"}'),
  ('id:"cv831", es:"meta", nl:"doel; finish", tag:"cerv-waar", sl:"meta"}',
   'id:"cv831", es:"meta", nl:"doel", tag:"cerv-waar", sl:"meta", meer:"finish"}'),
  ('id:"cv835", es:"civil", nl:"burger-; burgerlijk", tag:"cerv-politiek", sl:"civil"}',
   'id:"cv835", es:"civil", nl:"burger-", tag:"cerv-politiek", sl:"civil", meer:"burgerlijk"}'),
  ('id:"cv840", es:"violación", nl:"verkrachting; schending", tag:"cerv-diensten", sl:"violacion"}',
   'id:"cv840", es:"violación", nl:"verkrachting", tag:"cerv-diensten", sl:"violacion", meer:"schending"}'),
  ('id:"cv856", es:"lima", nl:"limoen; vijl", tag:"cerv-gezondheid", sl:"lima"}',
   'id:"cv856", es:"lima", nl:"limoen", tag:"cerv-gezondheid", sl:"lima", meer:"vijl"}'),
  ('id:"cv867", es:"cubo", nl:"emmer; kubus", tag:"cerv-reizen", sl:"cubo"}',
   'id:"cv867", es:"cubo", nl:"emmer", tag:"cerv-reizen", sl:"cubo", meer:"kubus"}'),
  ('id:"cv891", es:"columna", nl:"wervelkolom; kolom", tag:"cerv-lichaam", sl:"columna"}',
   'id:"cv891", es:"columna", nl:"wervelkolom", tag:"cerv-lichaam", sl:"columna", meer:"kolom"}'),
  ('id:"cv898", es:"gota", nl:"druppel; gicht", tag:"cerv-hoe", sl:"gota"}',
   'id:"cv898", es:"gota", nl:"druppel", tag:"cerv-hoe", sl:"gota", meer:"gicht"}'),
  ('id:"cv905", es:"pestaña", nl:"wimper; tabblad", tag:"cerv-lichaam", sl:"pestana"}',
   'id:"cv905", es:"pestaña", nl:"wimper", tag:"cerv-lichaam", sl:"pestana", meer:"tabblad"}'),
  ('id:"cv923", es:"taquilla", nl:"loket; kluisje", tag:"cerv-vrije-tijd", sl:"taquilla"}',
   'id:"cv923", es:"taquilla", nl:"loket", tag:"cerv-vrije-tijd", sl:"taquilla", meer:"kluisje"}'),
  ('id:"cv927", es:"borrador", nl:"klad; gum", tag:"cerv-school", sl:"borrador"}',
   'id:"cv927", es:"borrador", nl:"klad", tag:"cerv-school", sl:"borrador", meer:"gum"}'),
  ('id:"cv934", es:"ingreso", nl:"inkomen; storting", tag:"cerv-diensten", sl:"ingreso"}',
   'id:"cv934", es:"ingreso", nl:"inkomen", tag:"cerv-diensten", sl:"ingreso", meer:"storting"}'),
  ('id:"cv947", es:"amanecer", nl:"zonsopgang; dagen", tag:"cerv-wanneer", sl:"amanecer"}',
   'id:"cv947", es:"amanecer", nl:"zonsopgang", tag:"cerv-wanneer", sl:"amanecer", meer:"dagen"}'),
  ('id:"cv969", es:"etiqueta", nl:"label; etiquette", tag:"cerv-winkelen", sl:"etiqueta"}',
   'id:"cv969", es:"etiqueta", nl:"label", tag:"cerv-winkelen", sl:"etiqueta", meer:"etiquette"}'),
  ('id:"cv983", es:"adelantar", nl:"inhalen; vooruitzetten", tag:"cerv-reizen", sl:"adelantar"}',
   'id:"cv983", es:"adelantar", nl:"inhalen", tag:"cerv-reizen", sl:"adelantar", meer:"vooruitzetten"}'),
  ('id:"cv997", es:"doblar", nl:"dubbelvouwen; afslaan", tag:"cerv-hoe", sl:"doblar"}',
   'id:"cv997", es:"doblar", nl:"dubbelvouwen", tag:"cerv-hoe", sl:"doblar", meer:"afslaan"}'),
  ('id:"cv1011", es:"vencer", nl:"overwinnen; verlopen", tag:"cerv-vrije-tijd", sl:"vencer"}',
   'id:"cv1011", es:"vencer", nl:"overwinnen", tag:"cerv-vrije-tijd", sl:"vencer", meer:"verlopen"}'),
  ('id:"cv1012", es:"agotado", nl:"uitgeput; uitverkocht", tag:"cerv-bestaan", sl:"agotado"}',
   'id:"cv1012", es:"agotado", nl:"uitgeput", tag:"cerv-bestaan", sl:"agotado", meer:"uitverkocht"}'),
  ('id:"cv1023", es:"aficionado", nl:"fan; amateur", tag:"cerv-vrije-tijd", sl:"aficionado"}',
   'id:"cv1023", es:"aficionado", nl:"fan", tag:"cerv-vrije-tijd", sl:"aficionado", meer:"amateur"}'),
  ('id:"cv1025", es:"apostar", nl:"wedden; inzetten", tag:"cerv-vrije-tijd", sl:"apostar"}',
   'id:"cv1025", es:"apostar", nl:"wedden", tag:"cerv-vrije-tijd", sl:"apostar", meer:"inzetten"}'),
  ('id:"cv1029", es:"delantero", nl:"aanvaller; voorste", tag:"cerv-waar", sl:"delantero"}',
   'id:"cv1029", es:"delantero", nl:"aanvaller", tag:"cerv-waar", sl:"delantero", meer:"voorste"}'),
  ('id:"cv1030", es:"descargar", nl:"downloaden; ontladen", tag:"cerv-hoeveel", sl:"descargar"}',
   'id:"cv1030", es:"descargar", nl:"downloaden", tag:"cerv-hoeveel", sl:"descargar", meer:"ontladen"}'),
  ('id:"cv1037", es:"lanzamiento", nl:"release; worp", tag:"cerv-natuur", sl:"lanzamiento"}',
   'id:"cv1037", es:"lanzamiento", nl:"release", tag:"cerv-natuur", sl:"lanzamiento", meer:"worp"}'),
  ('id:"cv1039", es:"titular", nl:"kop (in de krant); basisspeler", tag:"cerv-media", sl:"titular"}',
   'id:"cv1039", es:"titular", nl:"kop (in de krant)", tag:"cerv-media", sl:"titular", meer:"basisspeler"}'),
  ('id:"cv1043", es:"declarar", nl:"verklaren; aangeven", tag:"cerv-media", sl:"declarar"}',
   'id:"cv1043", es:"declarar", nl:"verklaren", tag:"cerv-media", sl:"declarar", meer:"aangeven"}'),
  ('id:"cv1052", es:"aguja", nl:"naald; wijzer", tag:"cerv-winkelen", sl:"aguja"}',
   'id:"cv1052", es:"aguja", nl:"naald", tag:"cerv-winkelen", sl:"aguja", meer:"wijzer"}'),
  ('id:"cv1080", es:"personal", nl:"persoonlijk; personeel", tag:"cerv-gezondheid", sl:"personal"}',
   'id:"cv1080", es:"personal", nl:"persoonlijk", tag:"cerv-gezondheid", sl:"personal", meer:"personeel"}'),
  ('id:"cv1081", es:"oficial", nl:"officieel; officier", tag:"cerv-politiek", sl:"oficial"}',
   'id:"cv1081", es:"oficial", nl:"officieel", tag:"cerv-politiek", sl:"oficial", meer:"officier"}'),
  ('id:"cv1082", es:"nave", nl:"schip; nave espacial = ruimteschip", tag:"cerv-economie", sl:"nave"}',
   'id:"cv1082", es:"nave", nl:"schip", tag:"cerv-economie", sl:"nave", meer:"nave espacial = ruimteschip"}'),
  ('id:"cv1084", es:"anda", nl:"loop; toe nou (van andar)", tag:"cerv-wanneer", sl:"anda"}',
   'id:"cv1084", es:"anda", nl:"loop", tag:"cerv-wanneer", sl:"anda", meer:"toe nou (van andar)"}'),
  ('id:"cv1085", es:"salud", nl:"gezondheid; proost!", tag:"cerv-gezondheid", sl:"salud"}',
   'id:"cv1085", es:"salud", nl:"gezondheid", tag:"cerv-gezondheid", sl:"salud", meer:"proost!"}'),
  ('id:"cv1087", es:"conocido", nl:"bekend; kennis (persoon)", tag:"cerv-oordeel", sl:"conocido"}',
   'id:"cv1087", es:"conocido", nl:"bekend", tag:"cerv-oordeel", sl:"conocido", meer:"kennis (persoon)"}'),
  ('id:"cv1090", es:"departamento", nl:"appartement (Lat-Am); afdeling", tag:"cerv-economie", sl:"departamento"}',
   'id:"cv1090", es:"departamento", nl:"appartement (Lat-Am)", tag:"cerv-economie", sl:"departamento", meer:"afdeling"}'),
  ('id:"cv1091", es:"encuentro", nl:"ontmoeting; ik vind", tag:"cerv-vrije-tijd", sl:"encuentro"}',
   'id:"cv1091", es:"encuentro", nl:"ontmoeting", tag:"cerv-vrije-tijd", sl:"encuentro", meer:"ik vind"}'),
  ('id:"cv1092", es:"apuesto", nl:"ik wed (van apostar); knap", tag:"cerv-oordeel", sl:"apuesto"}',
   'id:"cv1092", es:"apuesto", nl:"ik wed (van apostar)", tag:"cerv-oordeel", sl:"apuesto", meer:"knap"}'),
  ('id:"cv1098", es:"turno", nl:"beurt; dienst (werk)", tag:"cerv-gezondheid", sl:"turno"}',
   'id:"cv1098", es:"turno", nl:"beurt", tag:"cerv-gezondheid", sl:"turno", meer:"dienst (werk)"}'),
  ('id:"cv1100", es:"caballero", nl:"heer; ridder", tag:"cerv-wie-je-bent", sl:"caballero"}',
   'id:"cv1100", es:"caballero", nl:"heer", tag:"cerv-wie-je-bent", sl:"caballero", meer:"ridder"}'),
  ('id:"cv1116", es:"declaración", nl:"verklaring; aangifte", tag:"cerv-media", sl:"declaracion"}',
   'id:"cv1116", es:"declaración", nl:"verklaring", tag:"cerv-media", sl:"declaracion", meer:"aangifte"}'),
  ('id:"cv1120", es:"molesto", nl:"vervelend, irritant; geïrriteerd", tag:"cerv-oordeel", sl:"molesto"}',
   'id:"cv1120", es:"molesto", nl:"vervelend, irritant", tag:"cerv-oordeel", sl:"molesto", meer:"geïrriteerd"}'),
  ('id:"cv1121", es:"aventura", nl:"avontuur; affaire", tag:"cerv-gevoel", sl:"aventura"}',
   'id:"cv1121", es:"aventura", nl:"avontuur", tag:"cerv-gevoel", sl:"aventura", meer:"affaire"}'),
  ('id:"cv1129", es:"charla", nl:"praatje, gesprek; lezing", tag:"cerv-school", sl:"charla"}',
   'id:"cv1129", es:"charla", nl:"praatje, gesprek", tag:"cerv-school", sl:"charla", meer:"lezing"}'),
  ('id:"cv1132", es:"copia", nl:"kopie; kopieer!", tag:"cerv-kunst", sl:"copia"}',
   'id:"cv1132", es:"copia", nl:"kopie", tag:"cerv-kunst", sl:"copia", meer:"kopieer!"}'),
  ('id:"cv1134", es:"lío", nl:"gedoe, rommel; affaire", tag:"cerv-oordeel", sl:"lio"}',
   'id:"cv1134", es:"lío", nl:"gedoe, rommel", tag:"cerv-oordeel", sl:"lio", meer:"affaire"}'),
  ('id:"cv1135", es:"medios", nl:"middelen; media", tag:"cerv-economie", sl:"medios"}',
   'id:"cv1135", es:"medios", nl:"middelen", tag:"cerv-economie", sl:"medios", meer:"media"}'),
  ('id:"cv1140", es:"cuerda", nl:"touw, koord; snaar", tag:"cerv-kunst", sl:"cuerda"}',
   'id:"cv1140", es:"cuerda", nl:"touw, koord", tag:"cerv-kunst", sl:"cuerda", meer:"snaar"}'),
  ('id:"cv1141", es:"seguido", nl:"achter elkaar; en seguida = meteen", tag:"cerv-wanneer", sl:"seguido"}',
   'id:"cv1141", es:"seguido", nl:"achter elkaar", tag:"cerv-wanneer", sl:"seguido", meer:"en seguida = meteen"}'),
  ('id:"cv1146", es:"audiencia", nl:"publiek; hoorzitting", tag:"cerv-bestaan", sl:"audiencia"}',
   'id:"cv1146", es:"audiencia", nl:"publiek", tag:"cerv-bestaan", sl:"audiencia", meer:"hoorzitting"}'),
  ('id:"cv1148", es:"título", nl:"titel; diploma", tag:"cerv-politiek", sl:"titulo"}',
   'id:"cv1148", es:"título", nl:"titel", tag:"cerv-politiek", sl:"titulo", meer:"diploma"}'),
  ('id:"cv1151", es:"patrón", nl:"baas; patroon", tag:"cerv-reizen", sl:"patron"}',
   'id:"cv1151", es:"patrón", nl:"baas", tag:"cerv-reizen", sl:"patron", meer:"patroon"}'),
  ('id:"cv1157", es:"alcance", nl:"bereik; al alcance = binnen bereik", tag:"cerv-oordeel", sl:"alcance"}',
   'id:"cv1157", es:"alcance", nl:"bereik", tag:"cerv-oordeel", sl:"alcance", meer:"al alcance = binnen bereik"}'),
  ('id:"cv1164", es:"picar", nl:"fijnsnijden; prikken; snacken", tag:"cerv-gezondheid", sl:"picar"}',
   'id:"cv1164", es:"picar", nl:"fijnsnijden", tag:"cerv-gezondheid", sl:"picar", meer:"prikken; snacken"}'),
  ('id:"cv1165", es:"revuelto", nl:"roerei; door elkaar", tag:"cerv-oordeel", sl:"revuelto"}',
   'id:"cv1165", es:"revuelto", nl:"roerei", tag:"cerv-oordeel", sl:"revuelto", meer:"door elkaar"}'),
  ('id:"cv1170", es:"ordenar", nl:"opruimen; bevelen", tag:"cerv-diensten", sl:"ordenar"}',
   'id:"cv1170", es:"ordenar", nl:"opruimen", tag:"cerv-diensten", sl:"ordenar", meer:"bevelen"}'),
  ('id:"cv1172", es:"tabla", nl:"plank; tabel", tag:"cerv-economie", sl:"tabla"}',
   'id:"cv1172", es:"tabla", nl:"plank", tag:"cerv-economie", sl:"tabla", meer:"tabel"}'),
  ('id:"cv1181", es:"pinchazo", nl:"prik; lekke band", tag:"cerv-reizen", sl:"pinchazo"}',
   'id:"cv1181", es:"pinchazo", nl:"prik", tag:"cerv-reizen", sl:"pinchazo", meer:"lekke band"}'),
  ('id:"cv1192", es:"faro", nl:"vuurtoren; koplamp", tag:"cerv-reizen", sl:"faro"}',
   'id:"cv1192", es:"faro", nl:"vuurtoren", tag:"cerv-reizen", sl:"faro", meer:"koplamp"}'),
  ('id:"cv1204", es:"plantilla", nl:"personeelsbestand; template", tag:"cerv-hoe", sl:"plantilla"}',
   'id:"cv1204", es:"plantilla", nl:"personeelsbestand", tag:"cerv-hoe", sl:"plantilla", meer:"template"}'),
  ('id:"cv1205", es:"renta", nl:"huur; inkomen", tag:"cerv-economie", sl:"renta"}',
   'id:"cv1205", es:"renta", nl:"huur", tag:"cerv-economie", sl:"renta", meer:"inkomen"}'),
  ('id:"cv1214", es:"cría", nl:"jong dier; het fokken", tag:"cerv-natuur", sl:"cria"}',
   'id:"cv1214", es:"cría", nl:"jong dier", tag:"cerv-natuur", sl:"cria", meer:"het fokken"}'),
  ('id:"cv1221", es:"botón", nl:"knoop; knop", tag:"cerv-media", sl:"boton"}',
   'id:"cv1221", es:"botón", nl:"knoop", tag:"cerv-media", sl:"boton", meer:"knop"}'),
  ('id:"cv1225", es:"puño", nl:"manchet; vuist", tag:"cerv-lichaam", sl:"puno"}',
   'id:"cv1225", es:"puño", nl:"manchet", tag:"cerv-lichaam", sl:"puno", meer:"vuist"}'),
  ('id:"cv1233", es:"padrino", nl:"peetvader; getuige", tag:"cerv-relaties", sl:"padrino"}',
   'id:"cv1233", es:"padrino", nl:"peetvader", tag:"cerv-relaties", sl:"padrino", meer:"getuige"}'),
  ('id:"cv1244", es:"reparar", nl:"repareren; opmerken", tag:"cerv-wonen", sl:"reparar"}',
   'id:"cv1244", es:"reparar", nl:"repareren", tag:"cerv-wonen", sl:"reparar", meer:"opmerken"}'),
  ('id:"cv1272", es:"patrimonio", nl:"erfgoed; vermogen", tag:"cerv-economie", sl:"patrimonio"}',
   'id:"cv1272", es:"patrimonio", nl:"erfgoed", tag:"cerv-economie", sl:"patrimonio", meer:"vermogen"}'),
  ('id:"cv1277", es:"contenido", nl:"inhoud; tevreden", tag:"cerv-bestaan", sl:"contenido"}',
   'id:"cv1277", es:"contenido", nl:"inhoud", tag:"cerv-bestaan", sl:"contenido", meer:"tevreden"}'),
  ('id:"cv1280", es:"hueco", nl:"gat, opening; hol", tag:"cerv-hoe", sl:"hueco"}',
   'id:"cv1280", es:"hueco", nl:"gat, opening", tag:"cerv-hoe", sl:"hueco", meer:"hol"}'),
  ('id:"cv1287", es:"acuerdo", nl:"akkoord; de acuerdo = oké", tag:"cerv-oordeel", sl:"acuerdo"}',
   'id:"cv1287", es:"acuerdo", nl:"akkoord", tag:"cerv-oordeel", sl:"acuerdo", meer:"de acuerdo = oké"}'),
  ('id:"cv1288", es:"tipo", nl:"type, soort; vent", tag:"cerv-economie", sl:"tipo"}',
   'id:"cv1288", es:"tipo", nl:"type, soort", tag:"cerv-economie", sl:"tipo", meer:"vent"}'),
  ('id:"cv1294", es:"pase", nl:"kom binnen (van pasar, beleefd); pas", tag:"cerv-vrije-tijd", sl:"pase"}',
   'id:"cv1294", es:"pase", nl:"kom binnen (van pasar, beleefd)", tag:"cerv-vrije-tijd", sl:"pase", meer:"pas"}'),
  ('id:"cv1296", es:"pruebas", nl:"bewijzen; testen", tag:"cerv-diensten", sl:"pruebas"}',
   'id:"cv1296", es:"pruebas", nl:"bewijzen", tag:"cerv-diensten", sl:"pruebas", meer:"testen"}'),
  ('id:"cv1302", es:"causa", nl:"oorzaak; a causa de = vanwege", tag:"cerv-politiek", sl:"causa"}',
   'id:"cv1302", es:"causa", nl:"oorzaak", tag:"cerv-politiek", sl:"causa", meer:"a causa de = vanwege"}'),
  ('id:"cv1306", es:"menudo", nl:"a menudo = vaak; ¡menudo...! = wat een...!", tag:"cerv-hoeveel", sl:"menudo"}',
   'id:"cv1306", es:"menudo", nl:"vaak", tag:"cerv-hoeveel", sl:"menudo", meer:"a menudo = vaak; ¡menudo...! = wat een...!"}'),
  ('id:"cv1309", es:"efecto", nl:"effect; en efecto = inderdaad", tag:"cerv-hoe", sl:"efecto"}',
   'id:"cv1309", es:"efecto", nl:"effect", tag:"cerv-hoe", sl:"efecto", meer:"en efecto = inderdaad"}'),
  ('id:"cv1310", es:"cinta", nl:"lint; band, tape", tag:"cerv-winkelen", sl:"cinta"}',
   'id:"cv1310", es:"cinta", nl:"lint", tag:"cerv-winkelen", sl:"cinta", meer:"band, tape"}'),
  ('id:"cv1312", es:"disparo", nl:"schot; ik schiet", tag:"cerv-vrije-tijd", sl:"disparo"}',
   'id:"cv1312", es:"disparo", nl:"schot", tag:"cerv-vrije-tijd", sl:"disparo", meer:"ik schiet"}'),
  ('id:"cv1314", es:"ruego", nl:"te lo ruego = ik smeek je (van rogar)", tag:"cerv-religie", sl:"ruego"}',
   'id:"cv1314", es:"ruego", nl:"ik smeek je (van rogar)", tag:"cerv-religie", sl:"ruego", meer:"te lo ruego = ik smeek je (van rogar)"}'),
  ('id:"cv1316", es:"grado", nl:"graad; rang", tag:"cerv-oordeel", sl:"grado"}',
   'id:"cv1316", es:"grado", nl:"graad", tag:"cerv-oordeel", sl:"grado", meer:"rang"}'),
  ('id:"cv1321", es:"condición", nl:"voorwaarde; conditie", tag:"cerv-relaties", sl:"condicion"}',
   'id:"cv1321", es:"condición", nl:"voorwaarde", tag:"cerv-relaties", sl:"condicion", meer:"conditie"}'),
  ('id:"cv1322", es:"aprecio", nl:"waardering; ik waardeer", tag:"cerv-gevoel", sl:"aprecio"}',
   'id:"cv1322", es:"aprecio", nl:"waardering", tag:"cerv-gevoel", sl:"aprecio", meer:"ik waardeer"}'),
  ('id:"cv1327", es:"hongo", nl:"zwam, schimmel; champignon (LatAm)", tag:"cerv-techniek", sl:"hongo"}',
   'id:"cv1327", es:"hongo", nl:"zwam, schimmel", tag:"cerv-techniek", sl:"hongo", meer:"champignon (LatAm)"}'),
  ('id:"cv1329", es:"plancha", nl:"grillplaat; strijkijzer", tag:"cerv-economie", sl:"plancha"}',
   'id:"cv1329", es:"plancha", nl:"grillplaat", tag:"cerv-economie", sl:"plancha", meer:"strijkijzer"}'),
  ('id:"cv1337", es:"ampolla", nl:"blaar; ampul", tag:"cerv-gezondheid", sl:"ampolla"}',
   'id:"cv1337", es:"ampolla", nl:"blaar", tag:"cerv-gezondheid", sl:"ampolla", meer:"ampul"}'),
  ('id:"cv1364", es:"pillar", nl:"snappen; betrappen (Sp.)", tag:"cerv-gezondheid", sl:"pillar"}',
   'id:"cv1364", es:"pillar", nl:"snappen", tag:"cerv-gezondheid", sl:"pillar", meer:"betrappen (Sp.)"}'),
  ('id:"cv1368", es:"partida", nl:"spelletje, partij; vertrek", tag:"cerv-economie", sl:"partida"}',
   'id:"cv1368", es:"partida", nl:"spelletje, partij", tag:"cerv-economie", sl:"partida", meer:"vertrek"}'),
  ('id:"cv1369", es:"puntuación", nl:"score; interpunctie", tag:"cerv-school", sl:"puntuacion"}',
   'id:"cv1369", es:"puntuación", nl:"score", tag:"cerv-school", sl:"puntuacion", meer:"interpunctie"}'),
  ('id:"k10", es:"los señores", nl:"de heren; meneer en mevrouw", tag:"kern-mensen", ej:"Los señores García llegan mañana.", ejnl:"De heer en mevrouw García komen morgen."}',
   'id:"k10", es:"los señores", nl:"de heren", tag:"kern-mensen", ej:"Los señores García llegan mañana.", ejnl:"De heer en mevrouw García komen morgen.", meer:"meneer en mevrouw"}'),
  ('id:"k14", es:"la dirección", nl:"het adres; de richting", tag:"kern-mensen", ej:"Escribe aquí tu dirección.", ejnl:"Schrijf hier je adres."}',
   'id:"k14", es:"la dirección", nl:"het adres", tag:"kern-mensen", ej:"Escribe aquí tu dirección.", ejnl:"Schrijf hier je adres.", meer:"de richting"}'),
  ('id:"k28", es:"el paseo", nl:"de wandeling; de boulevard", tag:"kern-mensen", ej:"Damos un paseo después de comer.", ejnl:"We maken een wandeling na het eten."}',
   'id:"k28", es:"el paseo", nl:"de wandeling", tag:"kern-mensen", ej:"Damos un paseo después de comer.", ejnl:"We maken een wandeling na het eten.", meer:"de boulevard"}'),
  ('id:"k54", es:"el estudio", nl:"de studio; de studeerkamer", tag:"kern-wonen", ej:"Vive sola en un estudio.", ejnl:"Ze woont alleen in een studio."}',
   'id:"k54", es:"el estudio", nl:"de studio", tag:"kern-wonen", ej:"Vive sola en un estudio.", ejnl:"Ze woont alleen in een studio.", meer:"de studeerkamer"}'),
  ('id:"k70", es:"la clase", nl:"de les; de klas", tag:"kern-school", ej:"Hoy no tenemos clase.", ejnl:"Vandaag hebben we geen les."}',
   'id:"k70", es:"la clase", nl:"de les", tag:"kern-school", ej:"Hoy no tenemos clase.", ejnl:"Vandaag hebben we geen les.", meer:"de klas"}'),
  ('id:"k95", es:"el campo", nl:"het platteland; het veld", tag:"kern-natuur", ej:"Los domingos vamos al campo.", ejnl:"Op zondag gaan we naar buiten, het land in."}',
   'id:"k95", es:"el campo", nl:"het platteland", tag:"kern-natuur", ej:"Los domingos vamos al campo.", ejnl:"Op zondag gaan we naar buiten, het land in.", meer:"het veld"}'),
  ('id:"k97", es:"la planta", nl:"de plant; de verdieping", tag:"kern-natuur", ej:"Riego las plantas los sábados.", ejnl:"Ik geef de planten water op zaterdag."}',
   'id:"k97", es:"la planta", nl:"de plant", tag:"kern-natuur", ej:"Riego las plantas los sábados.", ejnl:"Ik geef de planten water op zaterdag.", meer:"de verdieping"}'),
  ('id:"k127", es:"el papel", nl:"het papier; de rol", tag:"kern-diensten", ej:"Dame una hoja de papel.", ejnl:"Geef me een vel papier."}',
   'id:"k127", es:"el papel", nl:"het papier", tag:"kern-diensten", ej:"Dame una hoja de papel.", ejnl:"Geef me een vel papier.", meer:"de rol"}'),
  ('id:"k135", es:"el billete", nl:"het kaartje; het bankbiljet", tag:"kern-winkel", ej:"Saco un billete de ida y vuelta.", ejnl:"Ik koop een retourtje."}',
   'id:"k135", es:"el billete", nl:"het kaartje", tag:"kern-winkel", ej:"Saco un billete de ida y vuelta.", ejnl:"Ik koop een retourtje.", meer:"het bankbiljet"}'),
  ('id:"k136", es:"la salida", nl:"de uitgang; het vertrek", tag:"kern-winkel", ej:"La salida está a la derecha.", ejnl:"De uitgang is rechts."}',
   'id:"k136", es:"la salida", nl:"de uitgang", tag:"kern-winkel", ej:"La salida está a la derecha.", ejnl:"De uitgang is rechts.", meer:"het vertrek"}'),
  ('id:"k167", es:"la entrada", nl:"de ingang; het toegangskaartje", tag:"kern-eigenschap", ej:"Compramos las entradas por internet.", ejnl:"We kopen de kaartjes op internet."}',
   'id:"k167", es:"la entrada", nl:"de ingang", tag:"kern-eigenschap", ej:"Compramos las entradas por internet.", ejnl:"We kopen de kaartjes op internet.", meer:"het toegangskaartje"}'),
  ('id:"k169", es:"claro / clara", nl:"licht; duidelijk", tag:"kern-eigenschap", ej:"Prefiero el azul claro.", ejnl:"Ik heb liever lichtblauw."}',
   'id:"k169", es:"claro / clara", nl:"licht", tag:"kern-eigenschap", ej:"Prefiero el azul claro.", ejnl:"Ik heb liever lichtblauw.", meer:"duidelijk"}'),
  ('id:"k192", es:"el cine", nl:"de bioscoop; de film(kunst)", tag:"kern-kunst", ej:"Los martes el cine es más barato.", ejnl:"Op dinsdag is de bioscoop goedkoper."}',
   'id:"k192", es:"el cine", nl:"de bioscoop", tag:"kern-kunst", ej:"Los martes el cine es más barato.", ejnl:"Op dinsdag is de bioscoop goedkoper.", meer:"de film(kunst)"}'),
  ('id:"k219", es:"el guion", nl:"het streepje; het script", tag:"kern-media", ej:"Mi apellido lleva un guion.", ejnl:"In mijn achternaam zit een streepje."}',
   'id:"k219", es:"el guion", nl:"het streepje", tag:"kern-media", ej:"Mi apellido lleva un guion.", ejnl:"In mijn achternaam zit een streepje.", meer:"het script"}'),
  ('id:"k223", es:"bañarse", nl:"een bad nemen; zwemmen", tag:"kern-gezond", ej:"Nos bañamos en el mar.", ejnl:"We zwemmen in zee."}',
   'id:"k223", es:"bañarse", nl:"een bad nemen", tag:"kern-gezond", ej:"Nos bañamos en el mar.", ejnl:"We zwemmen in zee.", meer:"zwemmen"}'),
]

if DOE_APP:
    if A_ACHTER not in src:
        print("De achterkant van de woordkaart ziet er niet uit zoals verwacht.\n"
              "Deze patch bouwt op v23.99. Eerst bijtrekken:\n\n    git pull --rebase\n")
        sys.exit(1)
    ontbreekt = [i + 1 for i, p in enumerate(PAREN) if p[0] not in src]
    if ontbreekt:
        print("Deze index.html ziet er niet uit zoals verwacht; %d kaart(en) staan er niet zoals "
              "verwacht, de eerste is nummer %s.\nEerst bijtrekken:\n\n    git pull --rebase\n"
              % (len(ontbreekt), ontbreekt[0]))
        sys.exit(1)

    src = src.replace(A_ACHTER, N_ACHTER, 1)
    for a, b in PAREN:
        n = src.count(a)
        assert n == 1, "kaartanker komt %d keer voor in plaats van 1:\n%s" % (n, a[:160])
        src = src.replace(a, b, 1)

    src = re.sub(r'var APP_VERSIE = "[^"]+";', 'var APP_VERSIE = "%s";' % NIEUW, src, count=1)
    with io.open(PAD, "w", encoding="utf-8") as f:
        f.write(src)
    print("index.html gepatcht naar %s (%d kaarten)" % (NIEUW, len(PAREN)))
else:
    print("index.html was al gepatcht")

if DOE_VER:
    with io.open(PAD_VER, "w", encoding="utf-8") as f:
        f.write(NIEUW + "\n")
    print("versie.txt op %s" % NIEUW)
else:
    print("versie.txt stond al op %s" % NIEUW)
